import { GameState, CardInstance } from '@/types/game';

export const createCardInstance = (overrides: Partial<CardInstance> = {}): CardInstance => ({
  id: 'card-1',
  instanceId: 'card-1-instance',
  ownerId: 'player-1',
  location: 'hand',
  name: 'Test Shikigami',
  variant: 'Base',
  type: 'creature',
  faction: 'Tokyo',
  cost: 1,
  attack: 2,
  defense: 2,
  effect: 'Test effect',
  rarity: 'C',
  status: [],
  ...overrides,
});

export const createGameState = (overrides: Partial<GameState> = {}): GameState => ({
  id: 'game-1',
  players: [
    {
      id: 'player-1',
      name: 'Sorcerer',
      life: 20,
      energy: 5,
      ultimateEnergy: 0,
      deck: [],
      hand: [createCardInstance()],
      field: [],
      graveyard: [],
      exile: [],
      mulliganUsed: false,
    },
    {
      id: 'player-2',
      name: 'Cursed Spirit',
      life: 20,
      energy: 5,
      ultimateEnergy: 0,
      deck: [],
      hand: [],
      field: [],
      graveyard: [],
      exile: [],
      mulliganUsed: false,
    },
  ],
  currentPlayer: 0,
  turn: 1,
  phase: 'main1',
  stack: [],
  battleLog: ['Duel started'],
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
});
